A = 0        	// A's address 001E
B = 0	     	// B's address 001F	
COUNT = 0    	// C's address 0020
ZERO = 0	// D's address 0021
ONE = 1		// F's address 0022

BEGIN	RWD		// READ A
	STA	A
	BIP	NEXT
	BRU OUT		// IF A = 0, QUOTIENT = 0
	RWD		// READ B
	STA	B
	BIP INIT
	BRU	OUT	// IF B = 0, THEN BY DEFN QUOTIENT = 0
INIT	LDA	ZERO	// INITIALIZE QUOTIENT TO 0
	STA	COUNT
	LDA	B
	TCA
	STA B		// B = -B
LOOP	LDA	B
	ADD A		// A - i*B, i = NUMBER OF LOOPS
	STA	A
	BIN	FINISH	// RESULT NEGATIVE, FINISHED
			// DO NOT INCREMENT COUNTER
	BIP	OTHER
	LDA	COUNT	// REMAINDER IS ZERO
	ADD ONE
	BRU OUT1
FINISH	LDA	COUNT	// LOAD FINAL COUNT
	BRU	OUT1
OTHER	LDA COUNT	// INCREMENT QUOTIENT
	ADD ONE		// RESULT IS ZERO OR POSITIVE
	STA	COUNT
	BRU	LOOP
OUT	LDA ZERO
OUT1	WWD		// WRITE OUT RESULT
	HALT

