A = 0        	// A's address 001E
B = 0	     	// B's address 001F	
COUNT = 0    	// C's address 0020
ZERO = 0	// D's address 0021
ONE = 1		// F's address 0022

//not actual assembly: instruction knt added for testing clarity
0	BEGIN	RWD		// READ A
1		STA	A
2		BIP	NEXT
3		BRU OUT		// IF A = 0, QUOTIENT = 0
4	NEXT	RWD		// READ B
5		STA	B
6		BIP INIT
7		BRU	OUT	// IF B = 0, THEN BY DEFN QUOTIENT = 0
8	INIT	LDA	ZERO	// INITIALIZE QUOTIENT TO 0
9		STA	COUNT
10		LDA	B
11		TCA
12		STA B		// B = -B
13	LOOP	LDA	B
14		ADD A		// A - i*B, i = NUMBER OF LOOPS
15		STA	A
16		BIN	FINISH	// RESULT NEGATIVE, FINISHED
				// DO NOT INCREMENT COUNTER
17		BIP	OTHER
18		LDA	COUNT	// REMAINDER IS ZERO
19		ADD ONE
20		BRU OUT1
21	FINISH	LDA	COUNT	// LOAD FINAL COUNT
22		BRU	OUT1
23	OTHER	LDA COUNT	// INCREMENT QUOTIENT
24		ADD ONE		// RESULT IS ZERO OR POSITIVE
25		STA	COUNT
26		BRU	LOOP
27	OUT	LDA ZERO
28	OUT1	WWD		// WRITE OUT RESULT
29		HALT
